# Generated by Django 4.2.9 on 2024-01-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
