# Generated by Django 4.2.9 on 2024-01-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_loginhistory_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='hour',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='logout_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
