# Generated by Django 4.2.9 on 2024-01-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_loginhistory_hour_loginhistory_logout_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='hour',
        ),
    ]
