# Generated by Django 4.2.9 on 2024-01-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_loginhistory_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='is_auto_logged_out',
            field=models.BooleanField(default=False),
        ),
    ]
