# Generated by Django 4.2.9 on 2024-02-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_document_delete_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
